introduce command_custom option
robersonfaria/laravel-database-schedule pull request #3
Opened 2021-03-17 16:31 UTC by thyseus

2021-03-17 16:41 UTC, thyseus commented on src/Console/Scheduling/Schedule.php
> +			$command = $schedule->command;
nice ! will fix.

2021-03-17 16:43 UTC, thyseus commented on src/Console/Scheduling/Schedule.php
> +			$command = $schedule->command;
Ah, eyes up - executing a custom command needs to be called by `exec()`, not by `command()` ...

2021-03-17 16:52 UTC, robersonfaria requested changes
Your contribution is very good, thank you very much.

I just made a few observations, if you can change it or if you think we should do something different, I’m open to talk about it.

Thanks again for the contribution.

2021-03-17 16:52 UTC, robersonfaria commented on migrations/2021_03_16_171148_add_custom_command.php
> +		Schema::table('schedules', function (Blueprint $table) {
Here in the migration, the name of the table must use the field of the `config/database-schedule.php` configuration file

2021-03-17 16:52 UTC, robersonfaria commented on migrations/2021_03_16_171148_add_custom_command.php
> +		Schema::table('schedules', function (Blueprint $table) {
here the same thing

2021-03-17 16:52 UTC, robersonfaria commented on resources/views/form.blade.php
> +    <div v-if="form.command == 'custom'" class="form-group">
I believe that the options in the command field lacked the option `custom`.
Or did I misunderstand how to select a custom field?

2021-03-17 17:07 UTC, robersonfaria requested changes
for now these are the considerations.

Thank you very much

2021-03-18 08:32 UTC, thyseus commented on src/Console/Scheduling/Schedule.php
> +			$command = $schedule->command;
Thats clean code! Integrated it.

2021-03-18 13:33 UTC, robersonfaria approved these changes
Added the possibility to execute custom commands.

2021-03-18 13:34 UTC, merged